=== hegh/SimpleORM/sorm_codegen/src/main/resources/sorm.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://jonp.net/sorm"
            xmlns="http://jonp.net/sorm"
            elementFormDefault="qualified">


  







    <xsd:element name="sorm" type="sorm"></xsd:element>
    

    <xsd:complexType name="sorm">
      <xsd:sequence>
        <xsd:element name="field" type="field" maxOccurs="unbounded"
          minOccurs="1">
        </xsd:element>
        <xsd:element name="create" type="create" maxOccurs="1"
          minOccurs="0">
        </xsd:element>
        <xsd:element name="pk" type="pk" maxOccurs="1" minOccurs="0"></xsd:element>
        <xsd:element name="read" type="read" maxOccurs="1"
          minOccurs="0">
        </xsd:element>
        <xsd:element name="update" type="update" maxOccurs="1"
          minOccurs="0">
        </xsd:element>
        <xsd:element name="delete" type="delete" maxOccurs="1"
          minOccurs="0">
        </xsd:element>
        <xsd:element name="query" type="namedquery"
          maxOccurs="unbounded" minOccurs="0">
        </xsd:element>
      </xsd:sequence>
      <xsd:attribute name="pkg" type="xsd:string" use="required"></xsd:attribute>
      <xsd:attribute name="accessor" type="xsd:string" use="optional"
        default="public">
      </xsd:attribute>
      <xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
      <xsd:attribute name="orm-accessor" type="xsd:string"
        use="optional" default="public">
      </xsd:attribute>
      <xsd:attribute name="super" type="xsd:string" use="optional"></xsd:attribute>
    </xsd:complexType>
    <xsd:complexType name="field">
      <xsd:sequence>
        <xsd:element name="get" type="getter" minOccurs="0"
          maxOccurs="1">
        </xsd:element>
        <xsd:element name="set" type="setter" minOccurs="0"
          maxOccurs="1">
        </xsd:element>
        <xsd:element name="link" type="link" minOccurs="0"
          maxOccurs="1">
        </xsd:element>
      </xsd:sequence>
      <xsd:attribute name="accessor" type="xsd:string" use="optional"
        default="private">
      </xsd:attribute>
      <xsd:attribute name="type" type="xsd:string" use="required"></xsd:attribute>
      <xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
      <xsd:attribute name="primary" type="xsd:boolean" use="optional"
        default="false">
      </xsd:attribute>
      <xsd:attribute name="sql-type" type="xsd:string" use="optional"></xsd:attribute>
      <xsd:attribute name="sql-column" type="xsd:string"
        use="optional">
      </xsd:attribute>
      <xsd:attribute name="nullable" type="xsd:boolean" use="optional"
        default="false">
      </xsd:attribute>
      <xsd:attribute name="from-super" type="xsd:boolean" use="optional" default="false"></xsd:attribute>
      <xsd:attribute name="group" type="xsd:boolean" default="false"></xsd:attribute>
      <xsd:attribute name="parent" type="xsd:string"></xsd:attribute>
    </xsd:complexType>
    <xsd:complexType name="getter">
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute name="name" type="xsd:string" use="optional"></xsd:attribute>
          <xsd:attribute name="accessor" type="xsd:string"
            use="optional" default="public">
          </xsd:attribute>
          <xsd:attribute name="override" type="xsd:boolean"
            use="optional" default="false">
          </xsd:attribute>
          <xsd:attribute name="use-super" type="xsd:boolean" use="optional" default="false"></xsd:attribute>
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
    <xsd:complexType name="setter">
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute name="name" type="xsd:string" use="optional"></xsd:attribute>
          <xsd:attribute name="accessor" type="xsd:string"
            use="optional" fixed="public">
          </xsd:attribute>
          <xsd:attribute name="override" type="xsd:boolean"
            use="optional" default="false">
          </xsd:attribute>
          <xsd:attribute name="use-super" type="xsd:boolean" use="optional" default="false"></xsd:attribute>
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
    <xsd:complexType name="read">
      <xsd:sequence>
        <xsd:element name="r" type="query" minOccurs="1" maxOccurs="unbounded"></xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="query">
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute name="dialect" type="xsd:string" use="optional" default="*"></xsd:attribute>
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="create">
      <xsd:sequence>
        <xsd:element name="c" type="query" minOccurs="1" maxOccurs="unbounded"></xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="update">
      <xsd:sequence>
        <xsd:element name="u" type="query" minOccurs="1" maxOccurs="unbounded"></xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="delete">
      <xsd:sequence>
        <xsd:element name="d" type="query" minOccurs="1" maxOccurs="unbounded"></xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="pk">
      <xsd:sequence>
        <xsd:element name="pk" type="query" minOccurs="1" maxOccurs="unbounded"></xsd:element>
      </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="collection">
      <xsd:sequence>
        <xsd:element name="read" type="read" minOccurs="1" maxOccurs="1"></xsd:element>
        <xsd:element name="create" type="create" minOccurs="0" maxOccurs="1"></xsd:element>
        <xsd:element name="delete" type="delete" minOccurs="0" maxOccurs="1"></xsd:element>
      </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="link">
      <xsd:sequence>
        <xsd:element name="collection" type="collection" minOccurs="0"
          maxOccurs="1">
        </xsd:element>
      </xsd:sequence>
      <xsd:attribute name="mode" type="xsd:string" use="required"></xsd:attribute>
      <xsd:attribute name="key-type" type="xsd:string" use="required"></xsd:attribute>
      <xsd:attribute name="type" type="xsd:string" use="required"></xsd:attribute>
      <xsd:attribute name="sql-type" type="xsd:string" use="optional"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="namedquery">
      <xsd:sequence>
        <xsd:element name="param" type="param" minOccurs="0"
          maxOccurs="unbounded">
        </xsd:element>
        <xsd:element name="q" type="query" maxOccurs="unbounded" minOccurs="1"></xsd:element>
      </xsd:sequence>
      <xsd:attribute name="accessor" type="xsd:string" use="optional" default="public"></xsd:attribute>
      <xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>
    
    <xsd:complexType name="param">
      <xsd:sequence>
        <xsd:element name="set" type="xsd:string" minOccurs="0" maxOccurs="1"></xsd:element>
      </xsd:sequence>
      <xsd:attribute name="type" type="xsd:string" use="required"></xsd:attribute>
      <xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
      <xsd:attribute name="sql-type" type="xsd:string" use="optional"></xsd:attribute>
    </xsd:complexType>
</xsd:schema>

=== hegh/SimpleORM/sorm_test/src/test/sorm/person.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- vim:set expandtab shiftwidth=2 softtabstop=2 tabstop=8: -->
<sorm pkg="net.jonp.sorm.test"
      name="Person"
      super="net.jonp.sorm.test.PersonSuper"
      xmlns="http://jonp.net/sorm"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://jonp.net/sorm http://jonp.net/sorm/sorm.xsd">

    <field type="Integer" name="id" primary="true" />

    <field type="String" name="name" sql-type="String">
        <get override="true" />
    </field>

    <field type="Integer" name="mother" nullable="true">
        <link mode="ManyToOne" key-type="Integer" type="Person" />
    </field>

    <field type="Integer" name="father" nullable="true">
        <link mode="ManyToOne" key-type="Integer" type="Person" />
    </field>

    <field type="String" name="gender" sql-type="String" sql-column="sex">
        <get override="true" />
    </field>

    <field type="java.util.Date" name="dob" sql-type="Date">
        <get override="true">new java.sql.Date(%{}.getDob().getTime())</get>
        <set>%{}.setDob(new java.util.Date(%{dob}.getTime()))</set>
    </field>

    <field type="Integer" name="spouse" nullable="true">
        <link mode="OneToOne" key-type="Integer" type="Person" />
    </field>

    <field name="children" type="Collection&lt;Person&gt;">
        <link mode="OneToMany" key-type="Integer" type="Person">
            <collection>
                <read>
                    <r>
select id
  from person
 where mother = %{id}
    or father = %{id}
                    </r>
                </read>
            </collection>
        </link>
    </field>

    <field name="friends" type="Collection&lt;Person&gt;">
        <link mode="ManyToMany" key-type="Integer" type="Person">
            <collection>
                <read>
                    <r dialect="sqlite">
<!-- SQLite does not support multiple-insert, so it pays for that in longer selects -->
select person_id2 as id
  from friendmap
 where person_id1 = %{id}
union
select person_id1
  from friendmap
 where person_id2 = %{id}
                    </r>
                    <r dialect="*">
select person_id2 as id
  from friendmap
 where person_id1 = %{id}
                    </r>
                </read>
                <create>
                    <c dialect="sqlite">
<!-- SQLite only keeps a single pair because it does not support multiple-insert -->
insert
  into friendmap
  (person_id1, person_id2) values
  (%{1.id},    %{2.getId():Integer})
                    </c>
                    <c dialect="*">
insert
  into friendmap
  (person_id1, person_id2) values
  (%{1.id},                 %{2.getId():Integer}),
  (%{2.getId():Integer},    %{1.id})
                    </c>
                </create>
                <delete>
                    <d>
delete
  from friendmap
 where (person_id1 = %{1.id}
    and person_id2 = %{2.getId():Integer})
    or (person_id1 = %{2.getId():Integer}
    and person_id2 = %{1.id})
                    </d>
                </delete>
            </collection>
        </link>
    </field>

    <create>
        <c>
insert into person (name,    mother,    father,    sex,       dob,    spouse)
            values (%{name}, %{mother}, %{father}, %{gender}, %{dob}, %{spouse})
        </c>
    </create>

    <pk>
        <pk dialect="h2">
            select currval('person_id_seq') as id
        </pk>
        <pk dialect="mysql">
            select last_insert_id() as id
        </pk>
        <pk dialect="postgresql">
            select currval('person_id_seq') as id
        </pk>
        <pk dialect="sqlite">
            select last_insert_rowid() as id
        </pk>
    </pk>

    <read>
        <r>
select name,
       mother,
       father,
       sex,
       dob,
       spouse
  from person
 where id = %{}
        </r>
    </read>

    <update>
        <u>
update person
   set name = %{name},
       mother = %{mother},
       father = %{father},
       sex = %{gender},
       dob = %{dob},
       spouse = %{spouse}
 where id = %{id}
        </u>
    </update>

    <delete>
        <d>
delete
  from person
 where id = %{id}
        </d>
    </delete>

    <query type="Person" name="getByGender">
        <param type="String" name="gender" />
        <q>
            select id from person where sex = %{gender}
        </q>
    </query>

    <query type="Person" name="getByDob">
        <param type="java.util.Date" name="dob" sql-type="Date">
            <set>new java.sql.Date(%{}.getTime())</set>
        </param>
        <q>
            select id from person where dob = %{dob}
        </q>
    </query>
</sorm>

=== hegh/SimpleORM/sorm_example/src/main/sorm/person.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- vim:set expandtab shiftwidth=2 softtabstop=2 tabstop=8: -->
<sorm pkg="net.jonp.sorm.example"
      name="Person"
      xmlns="http://jonp.net/sorm"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://jonp.net/sorm http://jonp.net/sorm/sorm.xsd">

    <field type="Integer" name="id" primary="true" />

    <field type="String" name="name" sql-type="String" />

    <field type="Address" name="address" group="true">
        <set>%{}.setAddress(new Address(%{address.number}, %{address.street}, %{address.apartment}, %{address.city}, %{address.state}, %{address.zipcode}))</set>
    </field>

    <field type="String" name="number" parent="address" sql-column="addr_number">
        <get>%{}.getNumber()</get>
    </field>

    <field type="String" name="street" parent="address" sql-column="addr_street">
        <get>%{}.getStreet()</get>
    </field>

    <field type="String" name="apartment" parent="address" sql-column="addr_apt" nullable="true">
        <get>%{}.getApartment()</get>
    </field>

    <field type="String" name="city" parent="address" sql-column="addr_city">
        <get>%{}.getCity()</get>
    </field>

    <field type="String" name="state" parent="address" sql-column="addr_state">
        <get>%{}.getState()</get>
    </field>

    <field type="String" name="zipcode" parent="address" sql-column="addr_zip">
        <get>%{}.getZipcode()</get>
    </field>

    <field type="Integer" name="mother" nullable="true">
        <link mode="ManyToOne" key-type="Integer" type="Person" />
    </field>

    <field type="Integer" name="father" nullable="true">
        <link mode="ManyToOne" key-type="Integer" type="Person" />
    </field>

    <field type="String" name="gender" sql-type="String" sql-column="sex" />

    <field type="java.util.Date" name="dob" sql-type="Date">
        <get>new java.sql.Date(%{}.getDob().getTime())</get>
        <set>%{}.setDob(new java.util.Date(%{dob}.getTime()))</set>
    </field>

    <field type="Integer" name="spouse" nullable="true">
        <link mode="OneToOne" key-type="Integer" type="Person" />
    </field>

    <field name="children" type="Collection&lt;Person&gt;">
        <link mode="OneToMany" key-type="Integer" type="Person">
            <collection>
                <read>
                    <r>
select id
  from person
 where mother = %{id}
    or father = %{id}
                    </r>
                </read>
            </collection>
        </link>
    </field>

    <field name="friends" type="Collection&lt;Person&gt;">
        <link mode="ManyToMany" key-type="Integer" type="Person">
            <collection>
                <read>
                    <r dialect="sqlite">
<!-- SQLite does not support multiple-insert, so it pays for that in longer selects -->
select person_id2 as id
  from friendmap
 where person_id1 = %{id}
union
select person_id1
  from friendmap
 where person_id2 = %{id}
                    </r>
                    <r dialect="*">
select person_id2 as id
  from friendmap
 where person_id1 = %{id}
                    </r>
                </read>
                <create>
                    <c dialect="sqlite">
<!-- SQLite only keeps a single pair because it does not support multiple-insert -->
insert
  into friendmap
  (person_id1, person_id2) values
  (%{1.id},    %{2.getId():Integer})
                    </c>
                    <c dialect="*">
insert
  into friendmap
  (person_id1, person_id2) values
  (%{1.id},                 %{2.getId():Integer}),
  (%{2.getId():Integer},    %{1.id})
                    </c>
                </create>
                <delete>
                    <d>
delete
  from friendmap
 where (person_id1 = %{1.id}
    and person_id2 = %{2.getId():Integer})
    or (person_id1 = %{2.getId():Integer}
    and person_id2 = %{1.id})
                    </d>
                </delete>
            </collection>
        </link>
    </field>

    <create>
        <c>
        <!-- TODO: Insert, read, and update address info, and add another query (byAddress) -->
insert into person (name,    mother,    father,    sex,       dob,    spouse,
                    addr_number,       addr_street,       addr_apt,
                    addr_city,       addr_state,       addr_zip)
            values (%{name}, %{mother}, %{father}, %{gender}, %{dob}, %{spouse},
                    %{address.number}, %{address.street}, %{address.apartment},
                    %{address.city}, %{address.state}, %{address.zipcode})
        </c>
    </create>

    <pk>
        <pk dialect="mysql">
            select last_insert_id() as id
        </pk>
        <pk dialect="postgresql">
            select curval('person_id_seq') as id
        </pk>
        <pk dialect="sqlite">
            select last_insert_rowid() as id
        </pk>
    </pk>

    <read>
        <r>
select name,
       mother,
       father,
       sex,
       dob,
       spouse,
       addr_number,
       addr_street,
       addr_apt,
       addr_city,
       addr_state,
       addr_zip
  from person
 where id = %{}
        </r>
    </read>

    <update>
        <u>
update person
   set name = %{name},
       mother = %{mother},
       father = %{father},
       sex = %{gender},
       dob = %{dob},
       spouse = %{spouse},
       addr_number = %{address.number},
       addr_street = %{address.street},
       addr_apt = %{address.apartment},
       addr_city = %{address.city},
       addr_state = %{address.state},
       addr_zip = %{address.zipcode}
 where id = %{id}
        </u>
    </update>

    <delete>
        <d>
delete
  from person
 where id = %{id}
        </d>
    </delete>

    <query name="getByGender">
        <param type="String" name="gender" />
        <q>
            select id from person where sex = %{gender}
        </q>
    </query>

    <query name="getByDob">
        <param type="java.util.Date" name="dob" sql-type="Date">
            <set>new java.sql.Date(%{}.getTime())</set>
        </param>
        <q>
            select id from person where dob = %{dob}
        </q>
    </query>

    <query name="getByAddress">
        <param type="String" name="number" />
        <param type="String" name="street" />
        <param type="String" name="apartment" />
        <param type="String" name="city" />
        <param type="String" name="state" />
        <param type="String" name="zipcode" />
        <q>
select id
  from person
 where addr_number = %{number}
   and addr_street = %{street}
   and addr_apt = %{apartment}
   and addr_city = %{city}
   and addr_state = %{state}
   and addr_zip = %{zipcode}
        </q>
    </query>
</sorm>
